model:
  model_name: EfficientMedNeXt_L
  dimension: 3d

  in_channels: 1
  out_channels: 1
  feature_size: 32 
  kernel_sizes: [1,3,5]
  strides: [1,1,1]
  n_decoder_channels: 32
  deep_supervision: True





