model:
  model_name: slim_unetr
  dimension: 3d

  in_channels: 1
  num_classes: 1
  embed_dim: 96 
  embedding_dim: 64 
  channels: [ 24, 48, 60 ]
  blocks: [ 1, 2, 3, 2 ]
  heads: [ 1, 2, 4, 4 ]
  r: [ 4, 2, 2, 1 ]
  dropout: 0.3




