model:
  model_name: TransBTS
  dimension: 3d

  in_channels: 1
  out_channels: 1
  patch_dim: 8
  embedding_dim: 512
  num_heads: 8
  num_layers: 4
  hidden_dim: 4096
  dropout_rate: 0.1
  attn_dropout_rate: 0.1
  _conv_repr: True
  _pe_type: 'learned'

  pretrained_weights: False
