model:
  model_name: UNETR_PP
  dimension: 3d

  in_channels: 1
  out_channels: 1

  feature_size: 32
  hidden_size: 256
  dims: [32, 64, 128, 256]
  num_heads: 4
  pos_embed: "perceptron"
  orm_name: "instance"

  dropout_rate: 0.0
  do_ds: False

