model:
  model_name: Unetr
  dimension: 3d

  in_channels: 1
  out_channels: 1


  feature_size: 16
  hidden_size: 768
  mlp_dim: 3072
  num_heads: 12
  proj_type: 'perceptron'      
  pos_embed_type: 'learnable'
  norm_name: 'instance'
  res_block: True
  