model:
  model_name: medformer
  dimension: 2d

  in_channels: 1
  out_channels: 1
  base_chan: 32
  map_size: 8
  conv_block: 'BasicBlock'
  conv_num: [2, 1, 0, 0, 0, 1, 2, 2]
  trans_num: [0, 1, 2, 2, 2, 1, 0, 0]
  num_heads: [1, 4, 8, 16, 8, 4, 1, 1]
  fusion_depth: 2
  fusion_dim: 512
  fusion_heads: 16
  expansion: 4
  attn_drop: 0.0
  proj_drop: 0.0
  proj_type: 'depthwise'
