model:
  model_name: 3DUXNET
  dimension: 3d

  in_channels: 1
  out_channels: 1
  depths: [2, 2, 2, 2] 
  feat_size: [48, 96, 192, 384]
  drop_path_rate: 0
  layer_scale_init_value: 1e-6
  spatial_dims: 3

  pretrained_weights: False # or path to pretrained model
  pretrain_classes: 5



