model:
  model_name: MedFormer
  dimension: 3d

  in_channels: 1
  out_channels: 1
  base_chan: 32
  conv_block: 'BasicBlock'

  down_scale: [[1,2,2], [1,2,2], [2,2,2], [2,2,2]] # coresponds to down1 down2 down3 down4
  kernel_size: [[1,3,3], [1,3,3], [3,3,3], [3,3,3], [3,3,3]] # coresponds to inconv, down1, down2, down3, down4
  norm: in
  act: relu
  map_size: [2, 6, 6]
  conv_num: [2,0,0,0, 0,0,2,2]
  trans_num: [0,2,2,2, 2,2,0,0]
  num_heads: [1,4,4,4, 4,4,1,1]
  expansion: 4
  fusion_depth: 2
  fusion_dim: 256
  fusion_heads: 4
  attn_drop: 0.
  proj_drop: 0.
  proj_type: 'depthwise'
  rel_pos: False
  se: True