model:
  model_name: UNetPP
  dimension: 3d

  in_channels: 1
  out_channels: 1
  base_chan: 32
  down_scale: [[1,2,2], [2,2,2], [2,2,2], [2,2,2]]
  kernel_size: [[1,3,3], [2,3,3], [3,3,3], [3,3,3], [3,3,3]]
  block: BasicBlock
  norm: in